# Change these first
owner: FirenzeDigital # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  # Firenze Digital
  - name: Firenze Digital Website
    url: https://firenze.digital
  # Liga Ardyti
  # - name: Liga Ardyti
  #   url: https://ligaardyti.com.ar
  # Andrisani
  - name: Andrisani Website
    url: https://www.andrisani.com.ar
  # - name: Andrisani Socios Admin
  #   url: https://socios.andrisani.com.ar

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.firenze.digital
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Firenze.Digital -  **Upptime** Status page."
  introMessage: This is a status page which uses **real-time** data multiples endpoints.
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://firenze.digital

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
