name: Delete Closed Issues (Manual)

on:
  workflow_dispatch:
    inputs:
      confirm_deletion:
        description: 'Confirm to delete all closed issues'
        required: true
        default: 'false'

jobs:
  delete_closed_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Delete closed issues
        if: ${{ github.event.inputs.confirm_deletion == 'true' }}
        run: |
          GITHUB_TOKEN=${{ secrets.GH_TOKEN_DELETE_ISSUE }}
          REPO_OWNER=${{ github.repository_owner }}
          REPO_NAME=${{ github.event.repository.name }}
          
          # Get all closed issues
          CLOSED_ISSUES=$(curl -s -X GET -G \
            -H "Accept: application/vnd.github.v3+json" \
            -d "state=closed" \
            "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/issues" | jq -r '.[].number')

          # Delete each closed issue
          for ISSUE_NUMBER in $CLOSED_ISSUES; do
            curl -X DELETE \
              -H "Authorization: token $GITHUB_TOKEN" \
              "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/issues/$ISSUE_NUMBER"
          done
