name: Delete Closed Issues

on:
  workflow_dispatch:
    inputs:
      confirm_deletion:
        description: 'Confirm to delete all closed issues'
        required: true
        default: 'false'

jobs:
  delete_closed_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Delete closed issues
        if: ${{ github.event.inputs.confirm_deletion == 'true' }}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN_DELETE_ISSUE }}
        run: |
          REPO_OWNER=${{ github.repository_owner }}
          REPO_NAME=${{ github.event.repository.name }}
          
          # Get all closed issues
          CLOSED_ISSUES=$(curl -s -X POST \
            -H "Authorization: bearer $GH_TOKEN" \
            -H "Accept: application/json" \
            -d '{"query":"query { repository(owner: \"$REPO_OWNER\", name: \"$REPO_NAME\") { issues(states: CLOSED, first: 100) { nodes { id } } } }"}' \
            https://api.github.com/graphql | jq -r '.data.repository.issues.nodes[].id')

          # Delete each closed issue
          for ISSUE_ID in $CLOSED_ISSUES; do
            curl -s -X POST \
              -H "Authorization: bearer $GH_TOKEN" \
              -H "Accept: application/json" \
              -d '{"query":"mutation { deleteIssue(input: {issueId: \"$ISSUE_ID\"}) { clientMutationId } }"}' \
              https://api.github.com/graphql
          done
