name: delete closed issue

on:
  workflow_dispatch:
    inputs:
      confirm_deletion:
        description: 'Confirm to delete all closed issues'
        required: true
        default: 'false'

jobs:
  delete-issue:
    if: ${{ github.event.inputs.confirm_deletion == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: vtcaregorodtcev/delete-issue@main
        with:
          github_token: ${{ secrets.GH_TOKEN_DELETE_ISSUE }}
          issue_node_id: ${{ github.event.issue.node_id }}
