name: delete closed issue
on:
  issues:
    types: [closed]
jobs:
  delete-issue:
    runs-on: ubuntu-latest
    steps:
      - uses: vtcaregorodtcev/delete-issue@main
        with:
          github_token: ${{ secrets.GH_TOKEN_DELETE_ISSUE }}
          issue_node_id: ${{ github.event.issue.node_id }}
