name: Delete Closed Issues (Manual)

on:
  workflow_dispatch:

jobs:
  delete-closed-issues:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install @octokit/rest
        run: npm install @octokit/rest
      - name: Install fetch polyfill (if needed)
        run: npm install node-fetch  # Or a preferred polyfill library
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GH_TOKEN_DELETE_ISSUE }}
          script: |
            const fetch = require('node-fetch');  # Import the polyfill
            const { Octokit } = require("@octokit/rest");
            const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });

            async function listClosedIssues() {
              const { data: issues } = await octokit.issues.listForRepo({
                owner: context.repo.owner,
                repo: context.repo.repo,
                state: 'closed'
              });
              return issues;
            }

            async function confirmDeletion(issues) {
              const confirmed = await core.getBoolean('Confirm deletion? (This action will permanently delete all closed issues!)');
              if (confirmed) {
                for (const issue of issues) {
                  await octokit.issues.delete({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: issue.number
                  });
                  console.log(`Deleted issue: #${issue.number} - ${issue.title}`);
                }
              } else {
                console.log('Deletion cancelled.');
              }
            }

            (async () => {
              const issues = await listClosedIssues();
              if (issues.length > 0) {
                console.log(`Found ${issues.length} closed issues:`);
                issues.forEach(issue => console.log(`  #${issue.number} - ${issue.title}`));
                await confirmDeletion(issues);
              } else {
                console.log('No closed issues found.');
              }
            })();
