name: Delete Closed Issues (Manual)

on:
  workflow_dispatch:

jobs:
  delete-closed-issues:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install @octokit/rest
        run: npm install @octokit/rest node-fetch
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GH_TOKEN_DELETE_ISSUE }}
          script: |
            const { Octokit } = require("@octokit/rest");
            const fetch = require("node-fetch");
            const octokit = new Octokit({ auth: process.env.INPUT_GITHUB_TOKEN, request: { fetch } });
            async function listClosedIssues() {
              const { data: issues } = await octokit.issues.listForRepo({
                owner: context.repo.owner,
                repo: context.repo.repo,
                state: 'closed'
              });
              return issues;
            }
            async function confirmDeletion(issues) {
              const confirmed = true; // Manually triggering, always confirm
              if (confirmed) {
                for (const issue of issues) {
                  await octokit.issues.delete({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: issue.number
                  });
                  console.log(`Deleted issue: #${issue.number} - ${issue.title}`);
                }
              } else {
                console.log('Deletion cancelled.');
              }
            }
            (async () => {
              const issues = await listClosedIssues();
              if (issues.length > 0) {
                console.log(`Found ${issues.length} closed issues:`);
                issues.forEach(issue => console.log(`  #${issue.number} - ${issue.title}`));
                await confirmDeletion(issues);
              } else {
                console.log('No closed issues found.');
              }
            })();
